# 15641 SUPER SUPER BINARY SEARCH DELUXE 2.5: THE LEGEND OF THE GOLDEN MAZASSUMNIDA, EPISODE 2: THE MAZWAETL UNIVERSE, PART 2: THE PARALLEL UNIVERSE AND THE LOST MAZASSUMNIDA: GAME OF THE YEAR EDITION
# 임의의 자연수 프린트
# 정답보다 작은 수를 출력하면 33% 부근에서 "틀렸습니다"를 받는다.
# 정답보다 큰 수를 출력하면 66% 부근에서 "틀렸습니다"를 받는다.
# 정답 : 20